const getSrc = (fileName: string) =>
  `https://fytunrrwifmbhobjfpsp.supabase.co/storage/v1/object/public/effects/${fileName}`;

export const STICKERS = {
  effect1: [
    getSrc("effect1.png"),
    getSrc("effect2.png"),
    getSrc("effect3.png"),
    getSrc("effect4.png"),
    getSrc("effect5.png"),
    getSrc("effect6.png"),
    getSrc("effect7.png"),
    getSrc("effect8.png"),
    getSrc("effect9.png"),
    getSrc("effect10.png"),
    getSrc("effect11.png"),
    getSrc("effect12.png"),
  ],
  party: [
    getSrc("party1.gif"),
    getSrc("party2.gif"),
    getSrc("party3.gif"),
    getSrc("party4.gif"),
    getSrc("party5.gif"),
    getSrc("party1.gif"),
    getSrc("party2.gif"),
    getSrc("party3.gif"),
    getSrc("party4.gif"),
    getSrc("party5.gif"),
  ],
  star: [
    getSrc("star1.gif"),
    getSrc("star2.gif"),
    getSrc("star3.gif"),
    getSrc("star4.gif"),
    getSrc("star1.gif"),
    getSrc("star2.gif"),
    getSrc("star3.gif"),
    getSrc("star4.gif"),
  ],
  gift: [
    getSrc("gift1.gif"),
    getSrc("gift2.gif"),
    getSrc("gift3.gif"),
    getSrc("gift4.gif"),
    getSrc("gift5.gif"),
    getSrc("gift1.gif"),
    getSrc("gift2.gif"),
    getSrc("gift3.gif"),
    getSrc("gift4.gif"),
    getSrc("gift5.gif"),
    getSrc("gift1.gif"),
  ],
} as const;
